/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ..\models\Basic Spaceship.glb --output output\Basic Spaceship.js --keepnames --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/J-Toastie/Models/Basic Spaceship.glb`;

export function ModelJToastieBasicSpaceship(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group name="Spaceship" position={[0, 3.481, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[68.721, 68.721, 81.601]}>
        <mesh name="Spaceship_1" castShadow receiveShadow geometry={nodes.Spaceship_1.geometry} material={materials.orange} />
        <mesh name="Spaceship_2" castShadow receiveShadow geometry={nodes.Spaceship_2.geometry} material={materials.black} />
        <mesh name="Spaceship_3" castShadow receiveShadow geometry={nodes.Spaceship_3.geometry} material={materials.white} />
        <mesh name="Spaceship_4" castShadow receiveShadow geometry={nodes.Spaceship_4.geometry} material={materials.grey} />
      </group>
    </group>
  )
}

useGLTF.preload(link)
