/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { degToRad } from 'three/src/math/MathUtils';

export default function LowPolyPinballMachine(props) {
    const { nodes, materials } = useGLTF('/models/pinball.glb')

    // Generate a random color on each mount
    const randomColorScreen = useMemo(() => {
        const randomHex = () => '#' + Math.floor(Math.random()*16777215).toString(16).padStart(6, '0');
        return randomHex();
    }, []);

    // Generate a random color on each mount
    const randomColorGameBoard = useMemo(() => {
        const randomHex = () => '#' + Math.floor(Math.random()*16777215).toString(16).padStart(6, '0');
        return randomHex();
    }, []);

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials.Poliigon_WoodVeneerOak_7760_1K}
                position={[-2.86, 4, 7.194]}
                scale={[0.336, 4, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={materials.Poliigon_MetalSteelBrushed_7174_1K}
                position={[0, 10.309, -0.772]}
                rotation={[0.286, 0, 0]}
                scale={[1, 1, 9.639]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002.geometry}
                material={materials.Poliigon_WoodVeneerOak_7760_1K}
                position={[-2.86, 4, -9.739]}
                scale={[0.354, 4, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube003.geometry}
                // material={materials.Screen}
                material-color={randomColorScreen}
                position={[-2.86, 16.353, -9.739]}
                scale={[1.135, 4, 1]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004.geometry}
                // material={materials['Game Screen']}
                material-color={randomColorGameBoard}
                // color="blue"
                position={[0, 9, -0.772]}
                rotation={[degToRad(197), 0, 0]}
                // side='double'
                scale={[1, 1, 9.639]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder.geometry}
                // material={materials['Left Paddle Button']}
                material-color={randomColorScreen}
                position={[-3.713, 8.767, 8.144]}
                scale={0.139}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001.geometry}
                // material={materials['Launch Button']}
                material-color={randomColorScreen}
                position={[3.646, 8.767, 8.144]}
                scale={0.23}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder002.geometry}
                // material={materials['Right Panel Button']}
                material-color={randomColorScreen}
                position={[-3.271, 8.767, 8.144]}
                scale={0.139}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube005.geometry}
                material={materials.Poliigon_WoodVeneerOak_7760_1K}
                position={[-2.926, 0, 7.222]}
                scale={0.468}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube006.geometry}
                material={materials['Poliigon_WoodVeneerOak_7760_1K.001']}
                position={[-2.926, 0, -9.753]}
                scale={0.468}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube007.geometry}
                material={materials.Poliigon_MetalSteelBrushed_7174_1K}
                position={[-2.86, 16.353, -9.548]}
                scale={[1.135, 4, 1]}
            />
        </group>
    )
}

useGLTF.preload('/models/pinball.glb')
