/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\SciFi.gltf --output output\SciFi.js --transform 
Files: models\SciFi.gltf [3.31MB] > E:\Downloads\women\output\SciFi-transformed.glb [776.62KB] (77%)
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { LoopRepeat } from 'three'

export function ModelSciFiWoman(props) {

  const { randomAnimation } = props

  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/SciFi-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (randomAnimation && actions && Object.keys(actions).length > 0) {
      const actionNames = Object.keys(actions)
      const randomAction = actionNames[Math.floor(Math.random() * actionNames.length)]
      actions[randomAction]?.reset().fadeIn(0.3).play()
      actions[randomAction].setLoop(LoopRepeat)
      return () => actions[randomAction]?.fadeOut(0.3).stop()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
        </group>
        <group name="SciFi_Body">
          <skinnedMesh name="Cube045" geometry={nodes.Cube045.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube045.skeleton} />
          <skinnedMesh name="Cube045_1" geometry={nodes.Cube045_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube045_1.skeleton} />
          <skinnedMesh name="Cube045_2" geometry={nodes.Cube045_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube045_2.skeleton} />
          <skinnedMesh name="Cube045_3" geometry={nodes.Cube045_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube045_3.skeleton} />
          <skinnedMesh name="Cube045_4" geometry={nodes.Cube045_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube045_4.skeleton} />
        </group>
        <group name="SciFi_Feet">
          <skinnedMesh name="Cube046" geometry={nodes.Cube046.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube046.skeleton} />
          <skinnedMesh name="Cube046_1" geometry={nodes.Cube046_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube046_1.skeleton} />
        </group>
        <group name="SciFi_Head">
          <skinnedMesh name="Cube028" geometry={nodes.Cube028.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube028.skeleton} />
          <skinnedMesh name="Cube028_1" geometry={nodes.Cube028_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube028_1.skeleton} />
          <skinnedMesh name="Cube028_2" geometry={nodes.Cube028_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube028_2.skeleton} />
          <skinnedMesh name="Cube028_3" geometry={nodes.Cube028_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube028_3.skeleton} />
          <skinnedMesh name="Cube028_4" geometry={nodes.Cube028_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube028_4.skeleton} />
        </group>
        <group name="SciFi_Legs">
          <skinnedMesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube010.skeleton} />
          <skinnedMesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube010_1.skeleton} />
          <skinnedMesh name="Cube010_2" geometry={nodes.Cube010_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube010_2.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/SciFi-transformed.glb')
