/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelAsteroid(props) {
  const { nodes, materials } = useGLTF('models/Space/Asteroid.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Asteroids_Mesh.geometry}
        material={materials.Asteroids_Mat}
      />
    </group>
  )
}

useGLTF.preload('models/Space/Asteroid.glb')
