/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelPlanetEarth(props) {
  const { nodes, materials } = useGLTF('models/Space/Earth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Earth1-Mesh'].geometry}
        material={materials['02___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Earth1-Mesh_1'].geometry}
        material={materials.Mat}
      />
    </group>
  )
}

useGLTF.preload('models/Space/Earth.glb')