/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelPlanetJupiter(props) {
  const { nodes, materials } = useGLTF('models/Space/Jupiter.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Jupiter.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('models/Space/Jupiter.glb')
