export const SCENE_OBJECTS = [
    {
        id: "statue-of-liberty",
        type: "liberty",
        label: "Statue of Liberty",
        position: [-0.91, 0, -1.65],
        rotation: [0, 0, 0],
        logic: {
            trigger: "toggle",
            targets: ["gutter-flap-left", "gutter-flap-right"],
        },
    },
    {
        id: "bumper-red",
        type: "bumper",
        label: "Red pop bumper",
        position: [-0.47, 0, -1.39],
        rotation: [0, 0, 0],
        color: "#cf2d42",
    },
    {
        id: "bumper-blue",
        type: "bumper",
        label: "Blue pop bumper",
        position: [0.35, 0, -1.43],
        rotation: [0, 0, 0],
        color: "#2469b8",
    },
    {
        id: "bumper-white",
        type: "bumper",
        label: "White pop bumper",
        position: [-0.05, 0, -0.65],
        rotation: [0, 0, 0],
        color: "#fff1d2",
    },
    {
        id: "post-red-upper-left",
        type: "post",
        label: "Red post upper left",
        position: [-0.88, 0, -0.88],
        rotation: [0, 0, 0],
        color: "#cf2d42",
    },
    {
        id: "post-blue-upper-right",
        type: "post",
        label: "Blue post upper right",
        position: [0.78, 0, -0.92],
        rotation: [0, 0, 0],
        color: "#2469b8",
    },
    {
        id: "post-white-mid-left",
        type: "post",
        label: "White post middle left",
        position: [-0.64, 0, -0.18],
        rotation: [0, 0, 0],
        color: "#fff1d2",
    },
    {
        id: "post-red-mid-right",
        type: "post",
        label: "Red post middle right",
        position: [0.48, 0, -0.12],
        rotation: [0, 0, 0],
        color: "#cf2d42",
    },
    {
        id: "post-blue-lower-left",
        type: "post",
        label: "Blue post lower left",
        position: [-0.72, 0, 0.34],
        rotation: [0, 0, 0],
        color: "#2469b8",
    },
    {
        id: "post-white-lower-right",
        type: "post",
        label: "White post lower right",
        position: [0.62, 0, 0.42],
        rotation: [0, 0, 0],
        color: "#fff1d2",
    },
    {
        id: "post-red-bottom-left",
        type: "post",
        label: "Red post bottom left",
        position: [-0.34, 0, 0.82],
        rotation: [0, 0, 0],
        color: "#cf2d42",
    },
    {
        id: "post-blue-bottom-right",
        type: "post",
        label: "Blue post bottom right",
        position: [0.24, 0, 1.03],
        rotation: [0, 0, 0],
        color: "#2469b8",
    },
    {
        id: "slingshot-left",
        type: "slingshot",
        label: "Left slingshot",
        position: [-0.7, 0, 1],
        rotation: [0, 0, 0],
        side: "left",
    },
    {
        id: "slingshot-right",
        type: "slingshot",
        label: "Right slingshot",
        position: [0.35, 0, 1],
        rotation: [0, 0, 0],
        side: "right",
    },
    {
        id: "gutter-flap-left",
        type: "gutterFlap",
        label: "Left gutter flap",
        position: [-1.245, 0.125, 1.72],
        rotation: [0, 0, 0],
        side: "left",
    },
    {
        id: "gutter-flap-right",
        type: "gutterFlap",
        label: "Right gutter flap",
        position: [0.94, 0.125, 1.72],
        rotation: [0, 0, 0],
        side: "right",
    },
    {
        id: "flipper-left",
        type: "flipper",
        label: "Left flipper",
        position: [-0.87, 0.12, 1.77],
        rotation: [0, 0, 0],
        side: "left",
    },
    {
        id: "flipper-right",
        type: "flipper",
        label: "Right flipper",
        position: [0.63, 0.12, 1.77],
        rotation: [0, 0, 0],
        side: "right",
    },
];
